export const whiteListed = [
  'amp-list',
  'template',
  'base',
  'input',
  'form',
  'textarea',
  'section',
  'iframe',
  'label',
  'a',
  'abbr',
  'acronym',
  'address',
  'amp-ad',
  'amp-anim',
  'amp-audio',
  'amp-carousel',
  'amp-fit-text',
  'amp-font',
  'amp-iframe',
  'amp-image-lightbox',
  'amp-img',
  'amp-instagram',
  'amp-lightbox',
  'amp-pixel',
  'amp-twitter',
  'amp-video',
  'amp-vine ',
  'amp-youtube',
  'article',
  'aside',
  'b',
  'bdi',
  'bdo',
  'blockquote',
  'body',
  'br',
  'button',
  'caption',
  'center',
  'circle',
  'cite',
  'clippath',
  'code',
  'col',
  'colgroup',
  'data',
  'dd',
  'defs',
  'del',
  'desc',
  'dfn',
  'dir',
  'div',
  'dl',
  'dt',
  'em',
  'figcaption',
  'figure',
  'filter',
  'footer',
  'g',
  'glyph',
  'glyphref',
  'h1',
  'h2',
  'h3',
  'h4',
  'h5',
  'h6',
  'head',
  'header',
  'hgroup',
  'hkern',
  'hr',
  'html',
  'i',
  'ins',
  'kbd ',
  'li',
  'line',
  'lineargradient',
  'link',
  'listing',
  'main',
  'mark',
  'marker',
  'mask',
  'meta',
  'multicol',
  'nav',
  'nextid',
  'nobr',
  'noscript',
  'ol',
  'p',
  'path',
  'pattern',
  'polygon',
  'polyline',
  'pre',
  'q',
  'radialgradient',
  'rb',
  'rect',
  'rp',
  'rt',
  'rtc',
  'ruby',
  's',
  'samp',
  'script',
  'section',
  'small',
  'source',
  'spacer',
  'span',
  'strike',
  'strong',
  'style',
  'sub',
  'sup',
  'svg',
  'symbol',
  'table',
  'tbody',
  'td',
  'text',
  'textpath',
  'tfoot',
  'th',
  'thead',
  'time',
  'title',
  'title',
  'tr',
  'tref',
  'tspan',
  'tt',
  'u',
  'ul',
  'use',
  'var',
  'view',
  'vkern',
  'wbr',
  'xmp',
];

export const cleanAttributes = [
  { tag: 'section', attr: 'appbackground' },
  { tag: 'div', attr: 'classname' },
  { tag: 'div', attr: 'ng-transclude' },
  { tag: 'div', attr: 'appbackground' },
  { tag: 'svg', attr: 'alt' },
  { tag: 'svg', attr: 'space' },
  { tag: 'div', attr: 'appscroll' },
  { tag: 'div', attr: 'matripple' },
  { tag: 'div', attr: 'mat-ripple' },
  { tag: 'a', attr: 'routerlink' },
  { tag: 'a', attr: 'target' },
  { tag: 'a', attr: 'routerlinkactive' },
  { tag: 'a', attr: 'noreferrer' },
  { tag: 'a', attr: 'noopener' },
  { tag: 'a', attr: 'nofollow' },
  { tag: 'a', attr: 'ui-sref' },
  { tag: 'a', attr: 'alt' },
  { tag: 'a', attr: 'target' },
  { tag: 'input', attr: 'formcontrolname' },
  { tag: 'input', attr: 'matinput' },
  { tag: 'button', attr: 'matsteppernext' },
  { tag: 'button', attr: 'mat-input' },
  { tag: 'button', attr: 'mat-button' },
  { tag: 'textarea', attr: 'mattextareaautosize' },
  { tag: 'textarea', attr: 'matinput' },
  { tag: 'textarea', attr: 'value' },
  { tag: '*', attr: 'ng-version' },
  { tag: '*', attr: 'onclick' },
  { tag: '*', attr: 'cass' },
];

export interface AmpComponent {
  version:string;
  attrib:string;
}

export const AmpComponents:{[key:string]:AmpComponent} = {
    "amp-list":  {
      "version":"0.1",
      "attrib":"custom-element"
    },
    "amp-state": {
      "version":"0.1",
      "attrib":"custom-element"
    },
    "amp-mustache":{
      "version":"0.2",
      "attrib":"custom-template"
    },
    "amp-analytics":{
      "version":"0.1",
      "attrib":"custom-element"
    },
    "amp-form":{
      "version":"0.1",
      "attrib":"custom-element"
    },
    "amp-bind":{
      "version":"0.1",
      "attrib":"custom-element"
    },
    "amp-install-serviceworker":{
      "version":"0.1",
      "attrib":"custom-element"
    },
}


export const htagElements = {
  A: 0,
  ABBR: 0,
  ACRONYM: 0,
  ADDRESS: 0,
  APPLET: 'unsafe',
  AREA: 'empty',
  B: 0,
  BASE: 'empty' + 'unsafe',
  BASEFONT: 'empty' + 'unsafe',
  BDO: 0,
  BIG: 0,
  BLOCKQUOTE: 0,
  BODY: 'endtag' + 'unsafe' + 'fold',
  BR: 'empty',
  BUTTON: 0,
  CANVAS: 0,
  CAPTION: 0,
  CENTER: 0,
  CITE: 0,
  CODE: 0,
  COL: 'empty',
  COLGROUP: 'endtag',
  DD: 'endtag',
  DEL: 0,
  DFN: 0,
  DIR: 0,
  DIV: 0,
  DL: 0,
  DT: 'endtag',
  EM: 0,
  FIELDSET: 0,
  FONT: 0,
  FORM: 0,
  FRAME: 'empty' + 'unsafe',
  FRAMESET: 'unsafe',
  H1: 0,
  H2: 0,
  H3: 0,
  H4: 0,
  H5: 0,
  H6: 0,
  HEAD: 'endtag' + 'unsafe' + 'fold',
  HR: 'empty',
  HTML: 'endtag' + 'unsafe' + 'fold',
  I: 0,
  IFRAME: 'unsafe' + 'cdata',
  IMG: 'empty',
  INPUT: 'empty',
  INS: 0,
  ISINDEX: 'empty' + 'unsafe',
  KBD: 0,
  LABEL: 0,
  LEGEND: 0,
  LI: 'endtag',
  LINK: 'empty' + 'unsafe',
  MAP: 0,
  MENU: 0,
  META: 'empty' + 'unsafe',
  NOFRAMES: 'unsafe' + 'cdata',
  // TODO(johannes): This used to read:
  // 'NOSCRIPT':'unsafe' +
  //  'cdata',
  //
  // It appears that the effect of that is that anything inside is
  // then considered cdata, so <noscript><style>foo</noscript></noscript>
  // never sees a style start tag / end tag event. But we must
  // recognize such style tags and they're also allowed by HTML, e.g. see:
  // https://developer.mozilla.org/en-US/docs/Web/HTML/Element/noscript
  // On a broader note this also means we may be missing other start/end
  // tag events inside elements marked as CDATA which our parser
  // should better reject. Yikes.
  NOSCRIPT: 'unsafe',
  OBJECT: 'unsafe',
  OL: 0,
  OPTGROUP: 0,
  OPTION: 'endtag',
  P: 'endtag',
  PARAM: 'empty' + 'unsafe',
  PRE: 0,
  Q: 0,
  S: 0,
  SAMP: 0,
  SCRIPT: 'unsafe' + 'cdata',
  SELECT: 0,
  SMALL: 0,
  SPAN: 0,
  STRIKE: 0,
  STRONG: 0,
  STYLE: 'unsafe' + 'cdata',
  SUB: 0,
  SUP: 0,
  TABLE: 0,
  TBODY: 'endtag',
  TD: 'endtag',
  TEXTAREA: 'rcdata',
  TFOOT: 'endtag',
  TH: 'endtag',
  THEAD: 'endtag',
  TITLE: 'rcdata' + 'unsafe',
  TR: 'endtag',
  TT: 0,
  U: 0,
  UL: 0,
  VAR: 0,
};
